/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/api/health': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/ready': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Database unavailable */
                503: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/journal': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Journal entries */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/observations': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: {
                    from?: string
                    to?: string
                    definitionIds?: string
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            data: {
                                id: string
                                definitionId: string
                                canonicalValue: number
                                canonicalUnit: string
                                originalValue: number
                                originalUnit: string
                                /** Format: date-time */
                                observedAt: string
                                /** Format: date-time */
                                endedAt?: string | null
                                sourceId?: string | null
                                externalId?: string | null
                                provider?: string | null
                                connector?: string | null
                                metadata?: {
                                    [key: string]: unknown
                                }
                                excluded: boolean
                                version: number
                            }[]
                        }
                    }
                }
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                        }
                    }
                }
            }
        }
        put?: never
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        /** Format: uuid */
                        id?: string
                        definitionId: string
                        /**
                         * @default number
                         * @enum {string}
                         */
                        valueType?: 'number' | 'text' | 'boolean' | 'category' | 'event'
                        value?: number
                        unit?: string
                        textValue?: string
                        detail?: string
                        booleanValue?: boolean
                        categoryValue?: string
                        title?: string
                        /** @enum {string} */
                        category?: 'Meals' | 'Activity' | 'Sleep' | 'Measurements' | 'Check-ins'
                        /** @default {} */
                        attributes?: {
                            [key: string]: unknown
                        }
                        /** Format: date-time */
                        observedAt: string
                        /** @default You */
                        source?: string
                    }
                }
            }
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            data: unknown
                        }
                    }
                }
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                        }
                    }
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/observations/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /** @description Deletes the canonical observation; compound meals also delete their nutrient component observations */
        delete: {
            parameters: {
                query?: never
                header?: never
                path: {
                    id: string
                }
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Observation not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        options?: never
        head?: never
        patch: {
            parameters: {
                query?: never
                header?: never
                path: {
                    id: string
                }
                cookie?: never
            }
            requestBody: {
                content: {
                    'application/json': {
                        excluded?: boolean
                        title?: string
                        textValue?: string
                        detail?: string
                        /** Format: date-time */
                        observedAt?: string
                        version: number
                    }
                }
            }
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            data: unknown
                        }
                    }
                }
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                        }
                    }
                }
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                        }
                    }
                }
            }
        }
        trace?: never
    }
    '/api/daily-metrics': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: {
                    from?: string
                    to?: string
                }
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            data: unknown[]
                        }
                    }
                }
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            error: string
                        }
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/metric-sources': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content: {
                        'application/json': {
                            data: {
                                definitionId: string
                                provider: string
                                connector: string | null
                            }[]
                        }
                    }
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/device/health-records': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Canonical Health Connect records accepted idempotently */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Device authentication failed */
                401: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/health-records/rebuild': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Rebuilt disposable observations and daily metrics from canonical records */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/meals': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Meals */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/meals/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /** @description Deletes a compound meal observation and all of its nutrient component observations */
        delete: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Meal not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        options?: never
        head?: never
        patch: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        trace?: never
    }
    '/api/plan-items': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /** @description Lists dated user intentions. Planned meals never contribute to health metrics until logged. */
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Plan items */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        /** @description Creates a planned meal referencing a saved food or recipe. */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Food or recipe not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/plan-items/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        delete: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Removed from plan */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Version conflict */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        options?: never
        head?: never
        patch: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Plan item not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Version conflict or fulfilled item */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        trace?: never
    }
    '/api/plan-items/{id}/skip': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Skips or restores a plan item without creating a health observation. */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Version conflict or fulfilled item */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/plan-items/{id}/log': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /** @description Atomically creates the canonical compound meal observation and links it as the result of the plan item. */
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Meal logged */
                201: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Plan item or reference not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Version conflict or already fulfilled */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/preferences': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Preferences */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        trace?: never
    }
    '/api/goals/evaluations': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Server-evaluated goals over effective observations */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/foods/{id}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post?: never
        /** @description Deletes a catalog food while preserving historical meal snapshots and refusing deletion while a recipe or active meal plan still references the food */
        delete: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Food not found */
                404: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
                /** @description Version conflict or food is used by a recipe or meal plan */
                409: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/foods/import': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        post: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Per-row food import result */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/food-catalog/barcode/{barcode}': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Normalized catalog food preview */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    '/api/food-catalog/search': {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get: {
            parameters: {
                query?: never
                header?: never
                path?: never
                cookie?: never
            }
            requestBody?: never
            responses: {
                /** @description Normalized catalog food previews */
                200: {
                    headers: {
                        [name: string]: unknown
                    }
                    content?: never
                }
            }
        }
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: never
    responses: never
    parameters: never
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
