package net.trackit.companion

// Generated by scripts/generate-api-types.ts from the TrackIt OpenAPI contract.
// Do not edit manually.
data class OpenApiEndpoint(
    val method: String,
    val path: String,
)

object OpenApiEndpoints {
    val DEVICE_CURSOR_PUT = OpenApiEndpoint("PUT", "/api/device/cursor")
    val DEVICE_HEALTH_RECORDS_POST = OpenApiEndpoint("POST", "/api/device/health-records")
    val DEVICE_HEALTH_RECORDS_RECONCILE_POST = OpenApiEndpoint("POST", "/api/device/health-records/reconcile")
    val DEVICE_STATUS_GET = OpenApiEndpoint("GET", "/api/device/status")
    val DEVICES_PAIR_REQUEST_POST = OpenApiEndpoint("POST", "/api/devices/pair/request")
}
